name: Test Helm charts

on:
  pull_request:
    branches: [ "main" ]

permissions:
  contents: write
  packages: write

jobs:

  build:
   
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Configure Git
      run: |
        git config user.name "$GITHUB_ACTOR"
        git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

    - name: Set up chart-testing
      uses: helm/chart-testing-action@v2.3.1

    - name: Lint Charts
      run: |
        ct lint --all --validate-maintainers=false --chart-dirs chart
      
    - name: Install Linted charts
      run: |
        ct install --all --chart-dirs chart
