name: Helm Chars

on:
  release:
    types: [published, edited]

permissions:
  contents: write
  packages: write

jobs:

  build:
   
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Configure Git
      run: |
        git config user.name "$GITHUB_ACTOR"
        git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

    - name: Package and Push helm charts
      run: |
        cd chart
        helm package .
        helm push helloworldv2-*.tgz oci://ghcr.io/ledu32/helm-chats
